accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

write/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('book/<slug:slug>', views.book, name='book'),
    path('add_book/', views.add_book, name='add_book'),
    path('edit_book/<slug:slug>', views.edit_book, name='edit_book'),
    path('chapter/<slug:slug>', views.chapter, name='chapter'),
    path('add_chapter/<slug:slug>', views.add_chapter, name='add_chapter'),
    path('edit_chapter/<slug:slug>', views.edit_chapter, name='edit_chapter'),
    path('add_note/<slug:slug>', views.add_notes, name='add_note'),
    path('edit_note/<note_id>', views.edit_notes, name='edit_note'),
]

writeit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('write.urls')),
    path('accounts/', include('accounts.urls')),
] 

templates/includes/footer.html
<footer class="footer mt-auto">
    <div class="container-md my-3">
        <div class="text-center">
        <h1 class="headings subheadings">
            &copy; Jay Collins
        </h1>
        </div>
    </div>
</footer>

templates/includes/header.html
<header>
    <nav class="nav-style container-fluid">
            <div class="col-12 d-flex justify-content-between">
                <div class="col headings">
                    <h1><a class="nav-links" href="{% url 'home' %}">Write It</a></h1>
                </div>
                <div>
                    {% if not user.is_authenticated %}
                    <a class="nav-links" href="{% url 'accounts:login' %}">Login</a>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <a class="nav-links" href="{% url 'accounts:logout' %}">Logout</a>
                    {% endif %}
                </div>
            </div>
    </nav>
</header>